app/models.py
from flask_login import UserMixin
from . import db, login_manager
from werkzeug.security import generate_password_hash,check_password_hash

class User(UserMixin,db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    blog = db.relationship('Blog', backref = 'username', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f' {self.username}'

class Blog(db.Model):

    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    blog = db.Column(db.String)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comment', backref='pitch', lazy='dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls, user_id):
        blog = Blog.query.filter_by(id=user_id).all()
        return blog

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String)
    author = db.Column(db.String(255))
    blog_id = db.Column(db.Integer, db.ForeignKey("blogs.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls, id):
        comment = Comment.query.filter_by(blog_id=id).all()
        return comment

class Subscriber(UserMixin, db.Model):
   __tablename__="subscribers"

   id = db.Column(db.Integer, primary_key=True)
   name = db.Column(db.String(255))
   email = db.Column(db.String(255),unique = True,index = True)


   def save_subscriber(self):
       db.session.add(self)
       db.session.commit()

   @classmethod
   def get_subscribers(cls,id):
       return Subscriber.query.all()


   def __repr__(self):
       return f'User {self.email}'

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Quote:
    def __init__(self,id,author,quote):
        self.id =id
        self.author = author
        self. quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):

    # title = StringField('Review title',validators=[Required()])
    # category = StringField('Write a pitch category', validators=[Required()])
    blog = TextAreaField('Write a blog', validators=[Required()])
    # author = StringField('enter your name', validators=[Required()])
    Submit = SubmitField('Submit')

class SubscriberForm(FlaskForm):
    name = StringField("Enter your name")
    email = StringField("Email", validators=[Required()])
    submit= SubmitField('Subscribe')

class CommentForm(FlaskForm):
    comment= TextAreaField('comment', validators=[Required()])
    author = StringField('enter your name', validators=[Required()])
    Submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options,DevConfig
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail




# Initializing application
app = Flask(__name__,instance_relative_config = True)

# Setting up configuration
app.config.from_object(DevConfig)




login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


db = SQLAlchemy()
bootstrap = Bootstrap()
photos = UploadSet('photos',IMAGES)
mail = Mail()


def create_app(config_name):
    app=Flask(__name__)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix ='/auth')

    #Creating the app configurations
    app.config.from_object(config_options[config_name])

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    

    #Registering the blueprint
    from.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #setting config
    # from .request import configure_request
    # configure_request(app)

    #Configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template, redirect,url_for,abort,request
from flask_login import login_required, current_user
from . import main
from .forms import BlogForm, CommentForm, SubscriberForm
from ..models import Blog, Comment, User, Subscriber, Quote
from ..email import mail_message
from .. import db
from ..request import get_quotes

# import markdown2

@main.route('/')
def index():
    '''
    function that returns the index page
    '''
    quote = get_quotes()
    blogs = Blog.query.all()
    return render_template('index.html', blogs = blogs, quote=quote)

@main.route('/new_blog', methods = ['GET','POST'])
@login_required
def new_blog():
   form  =BlogForm()

   if form.validate_on_submit():
       blog = form.blog.data

       new_blog = Blog(blog = blog, user_id = current_user.id)

       new_blog.save_blog()

       return redirect(url_for('main.index'))

   title = 'New Blog'
   return render_template('new_blog.html',title = title, blog_form = form)

@main.route('/comment/<id>')
def comment(id):
    '''
    function to return the comment
    '''
    comment = Comment.get_comment(id)
    print(comment)
    title = 'comments'
    return render_template('comment.html',title = title, comment = comment)

@main.route('/new_comment/<int:id>', methods = ['GET', 'POST'])
# @login_required
def new_comment(id):
    form = CommentForm()

    if form.validate_on_submit():
        writer = form.author.data
        comm = form.comment.data

        new_comment = Comment(comment = comm, blog_id = id, author= writer)
        new_comment.save_comment()

        return redirect(url_for('main.index'))

    title = 'New Comment'
    return render_template('new_comment.html', title = title, comment_form = form, pitch_id = id)

@main.route('/bloger/<uname>')
@login_required

def profile(uname):
    user = User.query.filter_by(username = uname).first()
    # abort(404)

    post = Blog.query.filter_by(user_id = current_user.id).all()
    print(post)


    title = uname

    return render_template('profile.html', user = user, blogs = post,title=title)

@main.route('/blog/<id>')
@login_required
def blog(id):

    post = Blog.query.filter_by(id=id).first()
    db.session.delete(post)
    db.session.commit()
    print(post)

    title = 'Delete blog'

    return render_template('delete.html', title = title, blogs = post)

# @main.route('/pro-comment/<id>')
# @login_required
# def viewcomment(id):
#     '''
#     function to return the comments
#     '''
#     comment = Comment.get_comment(id)
#     print(comment)
#     title = 'comments'
#     return render_template('pro-comment.html',title = title, comment = comment)

@main.route('/del-comment/<id>')
@login_required
def delcomment(id):
    '''
    function to delete comments
    '''
    comment = Comment.query.filter_by(id = id).first()
    db.session.delete(comment)
    db.session.commit()
    print(comment)
    title = 'delete comments'
    return render_template('delete.html',title = title, comment = comment)

@main.route('/subscribe',methods=["GET","POST"])
def subscriber():
    form=SubscriberForm()

    if form.validate_on_submit():
        subscriber = Subscriber(name=form.name.data,email=form.email.data)
        db.session.add(subscriber)
        db.session.commit()

        mail_message("Welcome to my blog","email/welcome_user",subscriber.email,subscriber=subscriber)
        return redirect(url_for('main.index'))
        title = 'Subscribe'
    return render_template('subscription.html',form=form)


@main.route('/blog/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_blog(id):
    """
    Edit a blogpost in the database
    """
    new_blog=False

    blog = Blog.query.get(id)
    form = BlogForm()

    if form.validate_on_submit():

        blog.blog = form.blog.data

        db.session.commit()

        print('edited comment ')


        return redirect(url_for('main.index'))

    form.blog.data = blog.blog


    return render_template('new_blog.html',action = 'Edit',new_blog = new_blog,blog_form = form,legend='Update Post')

app/templates/My-page.html
{% block content %}

<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="card-title">
        <h4>{{user.username}}</h4>
      </div>
      <div class="card-body">
        <p> Edit your Blogs</p>
      </div>
    </div>
  </div>
  {% for blog in blogs %}
  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <p>{{blog.blog}}</p>
        <a href="/pro-comment/{{blog.id}}"style="float:right">View Comments</a>


        <a href="/blog/edit/{{blog.id}}"style="text-align: centre;">Edit Blog</a>




        <a href="/blog/{{blog.id}}" style="color:red;">Delete Blog</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock%}

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Welcome to the best Movie Review website </title>
        {% endif %} 
        {% extends 'bootstrap/base.html'%}

        <!-- Navbar block  --> 
        {% block navbar %}
            {% include 'navbar.html' %}
        {% endblock %}
    </head>
    <body>
        <!-- Content block -->

        {% block content %}

        {% endblock%}
    </body>
</html>

app/templates/comment.html
{% extends 'base.html' %}

{% block content %}

<div class="card">

{% for  description in comment %}
<div class="container-fluid">
<div class="card-deck">
  <div style="text-align:center;">
  <div class="card-title">
    <h5><b>Author:</b> {{description.author}}</h5>
  </div>
  <!-- <div class="card-body"> -->
    <p><b>Comment: </b>{{description.comment}}</p>
  </div>
</div>
</div>
</div>


{% endfor %}

{% endblock %}

app/templates/delete.html
{% extends 'base.html' %}

{% block content %}

<p> <span style="color:red;"><b>has been deleted</b></span></p>



{% endblock %}

app/templates/fourOwfour.html
 {% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static',filename='CSS/index.css')}}">

{% endblock %}



{% block content %}

<a href="/subscribe" style="float:right;">subscribe</a>
<div class="container-fluid container">
  <h1>Welcome to the blogging web app, click here to write a blog &nbsp;<a class="btn btn-primary btn md" href="/new_blog" > New Blog</a></h1>
 
</div>
<div class="container">
<blockquote class="text-center text-lg">
    <h2>Random Quotes</h2>
    <p style="font-family:monospace;">{{quote.quote}}</p>
    <p style="font-family: monospace;"><b>Author:</b> {{quote.author}}</p>
    
  </div>
  <hr class="new1">
  
  <h3 style="text-align:center; font-family:monospace;">Read posted blogs here!</h3>
{% for blog in blogs %}

<div class="container-fluid">
  <div class="card-deck">
  <div class="card">
    <div class="card-header" style='text-align:center;'>
    </div>
    <div class="card-body">
      <p>Blog: {{blog.blog}}</p>
      <!-- <a class="btn btn-primary btn-md" href="/new_comment/{{blog.id}}">Add comment</a>
      <a class="btn btn-primary btn-md" href="/delete/{{blog.id}}">Delete blog</a>
      <a href="#" class="btn btn-primary a-btn-slide-text">
        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
         <span><strong>Delete blog</strong></span>            
     </a> -->


      <div class="row">
    <a href="/new_comment/{{blog.id}}" class="btn btn-primary a-btn-slide-text">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            <span><strong>Add comment</strong></span>            
        </a>
        <a href="/blog/edit/{{blog.id}}" class="btn btn-primary a-btn-slide-text">
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <span><strong>Edit a blog</strong></span>            
        </a>
        <a href="/comment/{{blog.id}}" class="btn btn-primary a-btn-slide-text">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
            <span><strong>View comments</strong></span>            
        </a>
        <a href="/blog/{{blog.id}}" class="btn btn-primary a-btn-slide-text">
           <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            <span><strong>Delete a blog</strong></span>            
        </a>
      </div>
    
     
  
    <!-- <a href="/comment/{{blog.id}}" class="comment">View Comments</a> -->
  </div>
    <!-- <br> -->
    <div class="card-footer">
      <div class="container-fluid write">
        
      </div>
    </div>
  </div>
  <br>
</div>
</div>

{% endfor %}
{% endblock %}

app/templates/macros.html
{% macro displayPitchList(pitch_list) %}
 {% for pitch in pitch_list %}

<div class="col-xs-6 col-sm-6 col-md-6">
  <div class="card m-2">
    <div class="card-header">
      Category - {{pitch.category}}
    </div>
    <div class="card-body">
      <h5 class="card-title">{{pitch.title}}</h5>
      <p class="card-text">{{pitch.category}}</p>
      <p class="card-text"><small class="text-muted">{{pitch.pitch}}</small></p>
      <hr>
      <p>Add a comment <a href="/comment/{{pitch.id}}">here</a>.</p>
    </div>
  </div>
</div>
{% endfor %} {% endmacro %}

    

app/templates/navbar.html
    <link rel="stylesheet" href="{{ url_for('static', filename='CSS/index.css') }}">
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <!-- <a class="navbar-brand" href="/"> <img src="https://cdn.pixabay.com/photo/2017/02/18/19/20/logo-2078018__340.png" width="80" height="80"> </a> -->
                <p><a class="navbar-brand" href="/"> Blog-App</a></p>
            </div>
            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Home</a></li></ul>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul> 
        </div>
    </div>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">

      {{ wtf.quick_form(blog_form) }}

    </div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
    <div class="container">

      {{ wtf.quick_form(comment_form) }}

    </div>

{% endblock %}

app/templates/new_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
        <div class="col-md-4">

            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>

{% endblock %}

app/templates/new_review.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">

        <div class="col-md-8">

            <img src="{{movie.poster}}" alt="{{movie.title}}" class="img-responsive">
        </div>

        <div class="col-md-4">

            {{ wtf.quick_form(review_form) }}
        </div>

    </div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}

    <div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>

    {% endif %}
    <br>
    <br>
    <br>
    <br>

        {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/search.html
<!-- {% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ movies| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayMovieList(movies)}}
            </ul>

        </div>

    </div>
{% endblock %} -->

app/templates/subscription.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf%}
<!-- Content block -->
{% block content %}
<title> {{ title }} </title>

<div class="container">

  <div class="row">

    <div class="col-md-2 col-lg-2">

    </div>

    <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-comment">

      {{ wtf.quick_form(form) }}

    </div>

    <div class="col-md-2 col-lg-2">

    </div>

  </div>
</div>
{% endblock %}